export const SUPABASEURL = 'https://fqtiwnljgjbvljlbxgxp.supabase.co';
export const SUPABASEKEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdGl3bmxqZ2pidmxqbGJ4Z3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjM5MzM3ODQsImV4cCI6MTk3OTUwOTc4NH0.34y6CQRJjcecvNhcM1j1V_BDpBy8rgyvcGY7h9_9DIA';
